#!/usr/bin/env bash
#displays Best School 10 times
i=l
while [ "$i" -le 10 ]
do
        if [ "$i" -eq 9]
        then
                echo "Best Schol"
                echo "Hi"
        else
                echo "Best School"
        fi
        i=$(( i + 1 ))
done
