#!/usr/bin/env bash
#displays the time for 12 hours and 59 minutes, display hours from 0 to 12 and minutes from 1 to 59

hour=0
minute=1

while [ $hour -le 12 ]; do
    while [ $minute -le 59 ]; do
        printf "%02d:%02d\n" "$hour" "$minute"
        ((minute++))
        if [ $minute -eq 60 ]; then
            ((hour++))
            minute=1
        fi
        if [ $(($hour * 60 + $minute)) -eq 71 ]; then
            exit 0
        fi
    done
done
